### ISSUE TITLE
How can i detect dragging on map?

### ISSUE THREAD

**Issue by topor00** [Unact/yandex_mapkit#108]
I need to detect, if user start or finish to dragging on map. Can it be able?

**Comment by DCrow** [comment]
Hello!

If I understand you correctly [`YandexMapController.enableCameraTracking`](https://github.com/Unact/yandex_mapkit/blob/master/lib/src/yandex_map_controller.dart#L186) should be what you are looking for.

It will return all camera changes. In this case when user changes current map camera position by dragging.
When your callback method receives a message with final = true dragging has been finished, otherwise it is still in progress.

**Comment by topor00** [comment]
Thanks, this is nice and simple solution!
