### ISSUE TITLE
No YandexSuggest after installation

### ISSUE THREAD

**Issue by nausharipov** [Unact/yandex_mapkit#141]
![IMAGE 2021-09-20 19:19:44](https://user-images.githubusercontent.com/31556582/134009239-6512ed95-44bb-4d2b-b4a9-4c1467d8c76b.jpg)

Why is there no src/yandex_suggest.dart in yandex_mapkit: ^1.1.1? How to use YandexSuggest?

**Comment by DCrow** [comment]
Hello!

You are looking at master branch of this project. 
`src/yandex_suggest.dart` isn't in 1.1.1, because it was created after that release. 
Everything after https://github.com/Unact/yandex_mapkit/commit/581f4900496d284b7fc1df53420971254ee1e7d5 hasn't been published to pub.dev. 
That functionality is currently under development.

PS. Suggestions are available in 1.1.1 in `src/yandex_suggest.dart`

**Comment by nausharipov** [comment]
@DCrow Hello! Thank you. 

Can you please clarify, what do you mean by "Suggestions are available in 1.1.1 in src/yandex_suggest.dart"?
There is no YandexSuggest in 1.1.1, as you mentioned before.

Is there a way to use YandexSuggest in Flutter or do I have to wait for an update?

**Comment by cream-cheeze** [comment]
In 1.1.1 it is called YandexSearch - it was renamed in later versions due to the new functionality.

**Comment by DCrow** [comment]
@nausharipov My mistake I meant `src/yandex_search.dart`. `YandexSearch.getSuggestions`
